config/routes.rb
Tedxrosslyn::Application.routes.draw do
  resources :applications

  resources :partners

  resources :talks

  resources :speakers

  match '/livestream' => "home#livestream", :as => "livestream"

  get "home/index"

  root :to => 'home#index'

end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :category, :logo, :name, :url, :img_name
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  http_basic_authenticate_with :name => "tedx", :password => "2030"
  layout "default"

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @partners }
    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @partner = Partner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/new
  # GET /partners/new.json
  def new
    @partner = Partner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/1/edit
  def edit
    @partner = Partner.find(params[:id])
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(params[:partner])

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render json: @partner, status: :created, location: @partner }
      else
        format.html { render action: "new" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /partners/1
  # PUT /partners/1.json
  def update
    @partner = Partner.find(params[:id])

    respond_to do |format|
      if @partner.update_attributes(params[:partner])
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
  <% if @partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% @partner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :img_name %><br />
    <%= f.text_field :img_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<div class="row panel">
  <div class="large-10 offset-large-5 columns">
	<h1>Editing partner</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @partner %> |
	<%= link_to 'Back', partners_path %>
  </div>
</div>

app/views/partners/index.html.erb
<h1>Listing partners</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Logo</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @partners.each do |partner| %>
  <tr>
    <td><%= partner.name %></td>
    <td><%= partner.category %></td>
    <td><%= partner.logo %></td>
    <td><%= partner.url %></td>
    <td><%= link_to 'Show', partner %></td>
    <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
    <td><%= button_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button radius" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Partner', new_partner_path %>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @partner.name %>
</p>

<p>
  <b>Category:</b>
  <%= @partner.category %>
</p>

<p>
  <b>Logo:</b>
  <%= @partner.logo %>
</p>

<p>
  <b>Url:</b>
  <%= @partner.url %>
</p>


<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>