config/routes.rb
Tedxrosslyn::Application.routes.draw do
  resources :applications

  resources :partners

  resources :talks

  resources :speakers

  match '/livestream' => "home#livestream", :as => "livestream"

  get "home/index"

  root :to => 'home#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :age, :email, :name, :question1, :question2, :question3, :question4, :question5, :question6, :twitter, :job_title

  validates :name, :presence => {:message => "Don't forget to put your name!" }, :length => { :maximum => 100, :message => "Don't forget to put your name!" } 
  validates :email, :presence => {:message => 'We need a real email to send you your ticket!' } , :email => {:message => 'We need a real email to send you your ticket!' }
  validates :question1, :presence => {:message => 'Please enter an answer' }
  validates :question2, :presence => {:message => 'Please enter an answer' }
  validates :question3, :presence => {:message => 'Please enter an answer' }
  validates :question4, :presence => {:message => 'Please enter an answer' }
  validates :question5, :presence => {:message => 'Please enter an answer' }
  validates :question6, :presence => {:message => 'Please enter an answer' }
  validates :job_title, :presence => {:message => 'Please enter a job title' }
  validates :age, :presence => {:message => 'How old are you?'}, :numericality => { :only_integer => true, :message => 'Please enter a number' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  
  before_filter :auth, :except => [:new, :create]

  layout "default", :except => [:new, :create, :edit, :update]

  def auth
     authenticate_or_request_with_http_basic do |username, password|
        username == "tedx" && password == "2030"
      end
  end

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html do 
          redirect_to root_path 
          flash[:application_success] = "true"
        end
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html do 
          render action: "new"
          flash[:notice] = 'Looks like there are still some areas to be fixed' 
          end 
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to root_path, notice: 'Application was successfully submitted.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<div class="row panel radius">
    <%= form_for @application, :validate => true  do |f| %>

      <h5 class="subheader">Please fill out the highlighted fields of your application</h5>

      <div class="field large-10 columns essay">
        <div class="small-3 columns">
          <label class="right inline tedx_red">Full Name </label>
        </div>
        <div class="small-9 columns">
        <%= f.text_field :name, :class => "show_error", :placeholder => 'Full Name' %>
          <% if @application.errors.any? %>
            <% @application.errors.full_messages.each do |msg| %>
              <%if msg == "Name can't be blank" %>
                <small class="error">Don't forget to put your name!</small>
              <% end %> 
            <% end %>
          <% end %>
          </div>
      </div>

      <div class="field large-10 columns">
        <div class="small-3 columns">
          <label class="right inline tedx_red"> Email Address </label>
        </div>
        <div class="small-9 columns temp_hidden">
          <%= f.text_field :email, :class => "show_error", :placeholder => 'Email Address' %>
            <% if @application.errors.any? %>
              <% @application.errors.full_messages.each do |msg| %>
                <%if msg == "Email is invalid" %>
                <small class="error hidden">We need a real email to send you your ticket!</small>
                  <% end %> 
              <% end %>
            <% end %>
        </div>
      </div>

      <div class="field large-10 columns">
        <div class="small-3 columns">
          <label class="right inline tedx_red"> Job Title </label>
        </div>
        <div class="small-4 columns left">
          <%= f.text_field :job_title, :placeholder => 'Job Title', :class => "show_highlight"  %>
        </div>

      </div>

      <div class="field large-10 columns">
        <div class="small-3 columns">
          <label class="right inline tedx_red"> Twitter </label>
        </div>
        <div class="small-3 columns left">
          <%= f.text_field :twitter, :placeholder => '@twiter' %>
        </div>
      </div>

      <div class="field large-10 columns">
        <div class="small-3 columns">
          <label class="right inline tedx_red"> Age </label>
        </div>
        <div class="small-3 columns left">
          <%= f.text_field :age, :placeholder => 'Age', :class => "show_highlight"  %>
        </div>
      </div>

        <div class="large-10 columns">
           <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> What are you currently spending most of your time thinking about? </label>
          </div>
          <div class="columns large-11">
            <%= f.text_area :question1, :class => "show_highlight" %>
          </div>
        </div>

        <div class="field large-10 columns">
          <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> What's your biggest achievement? </label>
          </div>
          <div class="columns large-11">
          <%= f.text_area :question2, :class => "show_highlight" %>
          </div>
        </div>

        <div class="field large-10 columns">
          <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> How can TEDxRosslyn help you? </label>
          </div>
          <div class="columns large-11">
            <%= f.text_area :question6, :class => "show_highlight"   %>
          </div>
        </div>

        <div class="field large-10 columns">
          <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> How can you help the TEDxRosslyn Community? </label>
          </div>
          <div class="columns large-11">
            <%= f.text_area :question3, :class => "show_highlight" %>
          </div>
        </div>

        <div class="field large-10 columns">
          <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> Additional Comments? </label>
          </div>
          <div class="columns large-11">
            <%= f.text_area :question4, :class => "show_highlight" %>
          </div>
        </div>

        <div class="field large-10 columns">
          <div class="columns large-10 large-offset-1">
            <label class="left inline tedx_red essay"> Lastly, and most importantly: what do you think will be the most popular ice cream flavor in the future? </label>
          </div>
          <div class="columns large-11">
            <%= f.text_area :question5, :class => "show_highlight"   %>
          </div>
        </div>

      <div class="field large-11 columns essay">
        <%= f.submit 'Apply' , :class => "button radius" %>
        <%= link_to 'Nevermind...', :back %>
      </div>
    <% end %>
</div>

app/views/applications/edit.html.erb
<h2 class="text-center">Your Application</h2>

<%= render 'form' %> 

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Twitter</th>
    <th>Job Title</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
    </tr>

    <% @applications.each do |application| %>
    <tr>
    <td><%= application.name %></td>
    <td><%= application.email %></td>
    <td><%= application.twitter %></td>
    <td><%= application.job_title %></td>
    <td><%= application.age %></td>
    <td><%= link_to 'Show', application, :class => "button radius success" %></td>
    <td><%= link_to 'Edit', edit_application_path(application), :class => "button radius secondary" %></td>
    <td><%= button_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button radius" %></td>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h2 class="text-center">Your Application</h2>

<%= render 'form' %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;"><%= @application.name %>'s Application</h1>

<p>
  <h5 class="subheader">Email:</h5>
  <%= @application.email %>
</p>

<p>
  <h5 class="subheader">Twitter:</h5>
  <%= @application.twitter %>
</p>

<p>
  <h5 class="subheader">Age:</h5>
  <%= @application.age %>
</p>

<p>
  <h5 class="subheader">Job Title:</h5>
  <%= @application.job_title %>
</p>

<p>
  <h5 class="subheader">What are you currently spending most of your time thinking about?</h5>
  <%= @application.question1 %>
</p>

<p>
  <h5 class="subheader">What's your biggest achievement?</h5>
  <%= @application.question2 %>
</p>

<p>
  <h5 class="subheader">How can TEDxRosslyn help you?</h5>
  <%= @application.question6 %>
</p>

<p>
  <h5 class="subheader">How can you help the TEDxRosslyn Community?</h5>
  <%= @application.question3 %>
</p>

<p>
  <h5 class="subheader">Additional Comments?</h5>
  <%= @application.question4 %>
</p>

<p>
  <h5 class="subheader">Lastly, and most importantly: what do you think will be the most popular ice cream flavor in the future?</h5>
  <%= @application.question5 %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>