config/routes.rb
Tedxrosslyn::Application.routes.draw do
  resources :applications

  resources :partners

  resources :talks

  resources :speakers

  match '/livestream' => "home#livestream", :as => "livestream"

  get "home/index"

  root :to => 'home#index'

end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :description, :speaker_id, :url

  belongs_to :speaker 
  has_many :speakers

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  http_basic_authenticate_with :name => "tedx", :password => "2030"
  layout "default"
  
  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talks }
    end
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    @talk = Talk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/new
  # GET /talks/new.json
  def new
    @talk = Talk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @talk }
    end
  end

  # GET /talks/1/edit
  def edit
    @talk = Talk.find(params[:id])
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(params[:talk])

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render json: @talk, status: :created, location: @talk }
      else
        format.html { render action: "new" }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /talks/1
  # PUT /talks/1.json
  def update
    @talk = Talk.find(params[:id])

    respond_to do |format|
      if @talk.update_attributes(params[:talk])
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_for(@talk) do |f| %>
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talk.errors.count, "error") %> prohibited this talk from being saved:</h2>

      <ul>
      <% @talk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speaker_id %><br />
    <%= f.number_field :speaker_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/talks/edit.html.erb
<h1>Editing talk</h1>

<%= render 'form' %>

<%= link_to 'Show', @talk %> |
<%= link_to 'Back', talks_path %>

app/views/talks/index.html.erb
<h1>Listing talks</h1>

<table>
  <tr>
    <th>Speaker</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @talks.each do |talk| %>
  <tr>
    <td><%= talk.speaker_id %></td>
    <td><%= talk.description %></td>
    <td><%= talk.url %></td>
    <td><%= link_to 'Show', talk %></td>
    <td><%= link_to 'Edit', edit_talk_path(talk) %></td>
    <td><%= button_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button radius" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<h1>New talk</h1>

<%= render 'form' %>

<%= link_to 'Back', talks_path %>

app/views/talks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Speaker:</b>
  <%= @talk.speaker_id %>
</p>

<p>
  <b>Description:</b>
  <%= @talk.description %>
</p>

<p>
  <b>Url:</b>
  <%= @talk.url %>
</p>


<%= link_to 'Edit', edit_talk_path(@talk) %> |
<%= link_to 'Back', talks_path %>