config/routes.rb
Tedxrosslyn::Application.routes.draw do
  resources :applications

  resources :partners

  resources :talks

  resources :speakers

  match '/livestream' => "home#livestream", :as => "livestream"

  get "home/index"

  root :to => 'home#index'

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  attr_accessible :bio, :link, :name, :speaker_type, :img_name

  has_many :talks
  
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  http_basic_authenticate_with :name => "tedx", :password => "2030"
  layout "default"

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @speakers }
    end
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @speaker }
    end
  end

  # GET /speakers/new
  # GET /speakers/new.json
  def new
    @speaker = Speaker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @speaker }
    end
  end

  # GET /speakers/1/edit
  def edit
    @speaker = Speaker.find(params[:id])
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(params[:speaker])

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: 'Speaker was successfully created.' }
        format.json { render json: @speaker, status: :created, location: @speaker }
      else
        format.html { render action: "new" }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /speakers/1
  # PUT /speakers/1.json
  def update
    @speaker = Speaker.find(params[:id])

    respond_to do |format|
      if @speaker.update_attributes(params[:speaker])
        format.html { redirect_to @speaker, notice: 'Speaker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker = Speaker.find(params[:id])
    @speaker.destroy

    respond_to do |format|
      format.html { redirect_to speakers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= form_for(@speaker) do |f| %>
  <% if @speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% @speaker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :speaker_type %><br />
    <%= f.text_field :speaker_type %>
  </div>
   <div class="field">
    <%= f.label :img_name %><br />
    <%= f.text_field :img_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
	<h1>Editing speaker</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @speaker %> |
	<%= link_to 'Back', speakers_path %>

app/views/speakers/index.html.erb
<h1>Listing speakers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Link</th>
    <th>Speaker type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @speakers.each do |speaker| %>
  <tr>
    <td><%= speaker.name %></td>
    <td><%= speaker.bio %></td>
    <td><%= speaker.link %></td>
    <td><%= speaker.speaker_type %></td>
    <td><%= link_to 'Show', speaker %></td>
    <td><%= link_to 'Edit', edit_speaker_path(speaker) %></td>
    <td><%= button_to 'Destroy', speaker, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button radius" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Speaker', new_speaker_path %>

app/views/speakers/new.html.erb
<h1>New speaker</h1>

<%= render 'form' %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @speaker.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @speaker.bio %>
</p>

<p>
  <b>Link:</b>
  <%= @speaker.link %>
</p>

<p>
  <b>Speaker type:</b>
  <%= @speaker.speaker_type %>
</p>


<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>